Upgrade
plone/mockup pull request #1334
Opened 2023-07-28 00:18 UTC by thet

2023-07-28 05:56 UTC, petschki requested changes

2023-07-28 05:56 UTC, petschki commented on package.json
> +        "jquery": "^3.7.0",
I tried that out a while ago, but this breaks the tests. Didn't look into details yet.

2023-07-30 19:52 UTC, petschki commented on package.json
> +        "jquery": "^3.7.0",
jQuery is not the problem. See comment below.

2023-07-30 19:53 UTC, petschki commented on package.json
> +        "sinon": "^15.2.0"
Turned out, that this sinon version has to be in `transformIgnorePattern` in jest config. Now tests are green again.

2023-07-30 19:55 UTC, petschki approved these changes

2023-07-30 19:55 UTC, merged

2023-07-31 09:05 UTC, thet commented
:tada: 

super!
I had a ton of breaking tests in mockup, glad that these were false flags...