Translate Close text as aria-label
plone/mockup pull request #1382
Opened 2024-05-16 08:27 UTC by erral

Fixes #1381 

@petschki can you check if this syntax is correct?

2024-05-16 08:46 UTC, petschki requested changes

2024-05-16 08:46 UTC, petschki commented on src/pat/modal/modal.js
> +                '        <button type="button" class="btn-close modal-close" aria-label="<%= _t("Close") %>"></button>' +
Unfortunately this doesn't work. You need to define a property, for example `tplObject.closeLabel` with the translated label and use it in the template like `<%= closeLabel %>`. See https://github.com/plone/mockup/blob/23f4d61cff105e946fea7feb5202da12bdce6ffe/src/pat/modal/modal.js#L392-L399 how its done with the other vars.

2024-06-12 08:29 UTC, petschki approved these changes

2024-06-12 08:31 UTC, merged

2024-06-12 14:41 UTC, erral commented
Sorry for leaving this unattended :(