Show 'Page 1 of 1' instead of 'Page 1 of 0'.
plone/mockup pull request #1413
Opened 2024-12-01 20:49 UTC by devdanzin

This trivial PR intends to fix https://github.com/plone/mockup/issues/1412 and https://github.com/plone/Products.CMFPlone/issues/3591 by checking that `totalPages` is zero and setting it to one.

2024-12-03 13:53 UTC, thet requested changes
Hi, thanks for the PR!

Some remarks though:

1) We're using automatic changelog generation based on commit messages using release-it, conventional-changelog and commitlint. Please change your commit message according to:
https://github.com/Patternslib/Patterns/blob/master/docs/developer/styleguide.md#commits-messages

2) See my code suggestion. I think it's simpler and I don't know if Backbone goes unnecessarily crazy when changing some state attributes too often. My simplification assigns the value in one go.

2024-12-03 13:53 UTC, thet commented on src/pat/structure/js/collections/result.js
> +        this.state.totalPages = this.state.totalPages === 0 ? 1 : this.state.totalPages;
```suggestion
        // Calculate the number of pages and set it to "1" if there are no results.
        this.state.totalPages = Math.ceil(response.total / state.pageSize) || 1;
```

2024-12-03 14:26 UTC, petschki commented
Looking at the issue, I'd recomment to completely remove the pagination when there is no result in the listing. Would make more sense to me. Btw. thank you @devdanzin for contributing! We were talking briefly at the conference about the `plone.protect` issue. Very much appreciated!

2024-12-04 13:25 UTC, devdanzin commented
Thank you very much for the review!

>     1. We're using automatic changelog generation based on commit messages

I've adapted your suggestion, please let me know if it should be improved.

>     2. See my code suggestion.

I tried @petschki's suggestion of not showing the pagination text and it looks better to me. Please let me know which option we should go with and whether the code makes sense.

2024-12-04 13:27 UTC, devdanzin commented
> I'd recomment to completely remove the pagination when there is no result in the listing.

Done, not sure whether it's better to leave the empty div or also make it conditional. I've left it in current form.

> Btw. thank you @devdanzin for contributing! We were talking briefly at the conference about the `plone.protect` issue.

Thank you for the review and for helping me at the sprint!

2024-12-07 15:38 UTC, thet approved these changes
Yes, not showing the pagination at all is even a better solution.
I lean towards not showing the div when there are no results because I favor simple, small and clean HTML output. But I'm OK with the current solution.

2024-12-09 07:22 UTC, petschki approved these changes

2024-12-09 08:37 UTC, merged